### ISSUE TITLE
Generate Javadoc for autogenerated methods generated by Lombok's @Builder

### ISSUE THREAD

**Issue by alibehzadian** [madhavd1/vscode-javadoc-tools#8] opened 2021-02-27 09:15 UTC
I have a Java class as below:

```java
@Setter @Getter @Builder @NoArgsConstructor @AllArgsConstructor
public class DocumentTypeInput {
    @NotNull @NotBlank
    private String name;
    private String description;      
}
```
When I run command `Generate Javadoc Comments for Open File`:

```java
@Setter @Getter 
/** 
 * @return DocumentTypeInputBuilder
 */
@Builder
/** 
 * @return String
 */
 @NoArgs
 /** 
  * @return String
  */
 Constructor @AllArgsConstructor
public class DocumentTypeInput {
    @NotNull @NotBlank
    private String name;
    private String description;      
}
```

**Comment by madhavd1** [comment] 2021-12-27 14:08
Duplicate of Issue #1

**Closed by madhavd1** 2021-12-27 14:08 UTC
